server:
  port: 8080
spring:
  application:
    name: tlias-web
    #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 123456
    #mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



